name: Selenium Grid Test

on:
  push:
     branches: [ "main" ]
  schedule:
    - cron: '00 5 * * *'
jobs:
  test:
    runs-on:  ${{ matrix.os }}
    env:
      TESTNG_XML: "web_testng.xml"
    services:
      selenium:
        image: selenium/standalone-chrome:4.1.0
        ports:
          - 4444:4444
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
        browser: [ chrome, safari ]
        include:
            - os: macos-latest
              browser: safari

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run Selenium Tests
        run: mvn clean test -DremoteDriverUrl=http://selenium:4444/wd/hub -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }} -DtestngXml=${{ env.TESTNG_XML }}
#        run: mvn clean test -DremoteDriverUrl=http://selenium:4444/wd/hub -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser }} -DtestngXml=$testngXml

