name: Selenium Grid Test

on:
  push:
     branches: [ "main" ]
  schedule:
    - cron: '00 5 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:4.1.0
        ports:
          - 4444:4444
    strategy:
      os: [ mac, windows ]
      browser:
          - name: Chrome
            version: latest
            os: ${{ matrix.os }}
          - name: Safari
            version: latest
            os: mac
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run Selenium Tests
        run: mvn test -DremoteDriverUrl=http://selenium:4444/wd/hub -Dos=${{ matrix.os }} -Dbrowser=${{ matrix.browser.name }} -DsuiteXmlFile=web_testng.xml
